import { Inter } from "next/font/google";
import { Analytics } from '@vercel/analytics/react';
import "@/app/globals.css";
import Navbar from "./Navbar/Navbar";
import NextTopLoader from "nextjs-toploader"

import Footer from "../../components/client/footer/Footer";
import ToastContainer from "@/components/toastify";
import "react-toastify/dist/ReactToastify.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <NextTopLoader />
  
        <Navbar  />
        <main className="mt-40">

        {children}
        </main>
        <Footer />
        <ToastContainer/>
        <Analytics />
      </body>
    </html>
  );
}
