export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import "@/app/globals.css";
import ToastContainer from "@/components/toastify";
import "react-toastify/dist/ReactToastify.css"
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>{children}
      <ToastContainer />
      </body>
    </html>
  )
}
